version: '3'
services:

    mysql:
        image: mysql:8.0.1
        container_name: mysql
        hostname: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        restart: always

    php:
        build:
            context: ./php-apache
        hostname: php
        container_name: php-apache
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - mysql:db
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql:db
        restart: always
